{% set name = "json2html" %}
{% set version = "1.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/json2html-{{ version }}.tar.gz
  sha256: 8951a53662ae9cfd812685facdba693fc950ffc1c1fd1a8a2d3cf4c34600689c

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - json2html
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/softvar/json2html
  summary: JSON to HTML Table Representation
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
